name: Publish Website to CPanel
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Clean cache
      run: npm cache clean -f
      
    - name: Delete node_modules
      run: rm -rf node_modules
      
    - name: remove package-lock.json
      run: rm -rf package-lock.json
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ${{ secrets.TINO_FTP_SERVER }}
        ftp-username: ${{ secrets.TINO_FTP_USERNAME }}
        ftp-password: ${{ secrets.TINO_FTP_PASSWORD }}
        protocol: ftps
        port: 21 